
language: go

install: go get -v github.com/gohugoio/hugo

script:
    - git clone "https://wanglics:${CO_TOKEN}@${CO_REF}" public
    - hugo version
    - hugo
    - cd ./public
    - git config user.name "indes"
    - git config user.email "wanglicsly@gmail.com"
    - git add .
    - git commit -m "Travis CI 自动部署"
    # Coding Pages
    - git push "https://wanglics:${CO_TOKEN}@${CO_REF}" master:master

deploy:
    
env:
    global:
        # Coding Pages
        - CO_REF: git.coding.net/indes/hesay_public.git    